baseURL = "http://www.kelt9.ch/"
languageCode = "de-ch"
title = "Kelt 9"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name    = "Startseite"
url     = "/"
weight  = 1
[[menu.main]]
name    = "Über uns"
url     = "about"
weight  = 2
[[menu.main]]
name    = "Dienstleistungen"
url     = "service"
weight  = 3
[[menu.main]]
name    = "Kontakt"
url     = "contact"
weight  = 4
[[menu.main]]
name    = "Impressum"
url     = "impressum"
weight  = 5

# Site Params
[params]
home = "Startseite"
logo = "images/logo.png"
dateFormat = "6 January 2006"
# Meta data
description = "Airspace Hugo theme"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io

# Banner Section
[params.banner]
enable  = false
bgImage = "images/slider.jpg"
heading = "HI, MY NAME IS JONATHON & I AM A"
description = "WITH 10 YEARS EXPERIENCE, I'VE OCCUPIED MANY ROLES INCLUDING DIGITAL DESIGN DIRECTOR, WEB DESIGNER AND DEVELOPER. THIS SITE SHOWCASES SOME OF MY WORK."
# button
btn     = true
btnText = "Download More"
btnURL  = "https://themefisher.com/"

# flip text
[[params.banner.flipText]]
title   = "DESIGNER"
[[params.banner.flipText]]
title   = "DEVELOPER"
[[params.banner.flipText]]
title   = "FATHER"

# Homepage About Section
[params.about]
enable  = true
title   = "Über die Firma Kelt 9"
content = "Kelt 9 ist Ihr Partner für effiziente und erfolgreiche IT-Projekte. Das Team bildet die komplette Bandbreite der Software-Entwicklung ab und ist seit mehreren Jahrzehnten in der Informatik tätig. Ob Business Analyse, Requirements Engineering, Projektleitung oder Software-Entwicklung – Wir bringen alles mit. Nach vielen Jahren als Angestellte von IT-Dienstleistungsfirmen, haben sich die Gründer dazu entschieden, in die Selbständigkeit zu starten. Kelt 9 freut sich auf die kommenden Herausforderungen und würde sich freuen, wenn Sie mit uns in Kontakt treten würden."
image   = "images/about/dev.jpg"

# Call to Action
[params.cta]
enable  = true
title   = "Haben wir Ihr Interesse geweckt?"
content = ""
btnText = "Zum Kontaktformular"
btnURL  = "/contact"

# Portfolio Section On Homepage
[params.portfolio]
enable  = true
title   = "Abgeschlossene Projekte"
subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

# social icon
[[params.socialIcon]]
icon = "ion-social-facebook"
url = "#"

[[params.socialIcon]]
icon = "ion-social-instagram"
url = "#"

[[params.socialIcon]]
icon = "ion-social-linkedin"
url = "#"

